"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { LayoutDashboard,FolderOpen,PanelsTopLeft,BriefcaseBusiness,Inbox,Settings,ArrowUpRight,Plus,Save,Check,ShieldCheck,LogOut,Search,ChevronRight,Images,Globe,FileText,Menu } from "lucide-react";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { approvedMediaUrl,type CMSDocument,type CMSProject } from "@/lib/cms-model";
import type { CMSState } from "@/lib/cms-store";
import { cloud } from "@/lib/content";

const sections=[
 {id:"overview",label:"Overview",icon:LayoutDashboard},{id:"projects",label:"Portfolio projects",icon:FolderOpen},
 {id:"website",label:"Website content",icon:PanelsTopLeft},{id:"services",label:"Services",icon:BriefcaseBusiness},
 {id:"enquiries",label:"Enquiry inbox",icon:Inbox},{id:"settings",label:"Publishing & access",icon:Settings}
];
const date=(v:string|null)=>v?new Date(v).toLocaleString():"Repository content";
type Enquiry={id:string;created_at:string;name:string;company:string;email:string;country:string;project_type:string;details:string};
function Field({label,value,onChange,multiline=false,hint,readOnly=false}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean;hint?:string;readOnly?:boolean}){
 return <label className="cp-field"><span>{label}</span>{multiline?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} readOnly={readOnly}/>:<input value={value} onChange={e=>onChange(e.target.value)} readOnly={readOnly}/>} {hint&&<small>{hint}</small>}</label>
}
function LineField({label,value,onChange,hint}:{label:string;value:string;onChange:(v:string)=>void;hint?:string}){
 const [buffer,setBuffer]=useState(value);
 return <Field label={label} value={buffer} multiline hint={hint} onChange={v=>{setBuffer(v);onChange(v)}}/>;
}
export function AdminConsole({local}:{local:boolean}){
 const [state,setState]=useState<CMSState|null>(null),[draft,setDraft]=useState<CMSDocument|null>(null);
 const [section,setSection]=useState("overview"),[selected,setSelected]=useState("001"),[query,setQuery]=useState(""),[filter,setFilter]=useState("all");
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[confirm,setConfirm]=useState(false),[nav,setNav]=useState(false);
 const [enquiries,setEnquiries]=useState<Enquiry[]>([]),[inboxError,setInboxError]=useState(""),[inboxLoading,setInboxLoading]=useState(false);
 const router=useRouter();
 const dirty=Boolean(draft&&state&&JSON.stringify(draft)!==JSON.stringify(state.draft));
 const unpublished=Boolean(draft&&state&&JSON.stringify(draft)!==JSON.stringify(state.published));
 useEffect(()=>{fetch("/api/admin/content",{cache:"no-store"}).then(async r=>{const d=await r.json() as CMSState & {error:string;enquiries:Enquiry[]};if(!r.ok)throw new Error(d.error);setState(d);setDraft(d.draft)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!dirty)return;const prevent=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener("beforeunload",prevent);return()=>window.removeEventListener("beforeunload",prevent)},[dirty]);
 useEffect(()=>{if(section!=="enquiries")return;let active=true;fetch("/api/admin/enquiries",{cache:"no-store"}).then(async r=>{const d=await r.json() as CMSState & {error:string;enquiries:Enquiry[]};if(!r.ok)throw new Error(d.error);if(active){setEnquiries(d.enquiries);setInboxError("")}}).catch(e=>{if(active)setInboxError(e.message)}).finally(()=>{if(active)setInboxLoading(false)});return()=>{active=false}},[section]);
 function navigate(id:string){if(id==="enquiries")setInboxLoading(true);setSection(id);setNav(false);setMessage("")}
 function setting<K extends keyof CMSDocument["settings"]>(key:K,value:CMSDocument["settings"][K]){if(draft)setDraft({...draft,settings:{...draft.settings,[key]:value}})}
 function editProject(patch:Partial<CMSProject>){if(draft)setDraft({...draft,projects:draft.projects.map(p=>p.code===selected?{...p,...patch}:p)})}
 function addProject(){if(!draft)return;const code=String(Math.max(0,...draft.projects.map(p=>Number(p.code)))+1).padStart(3,"0");
  const p:CMSProject={code,slug:"",title:"",type:"",category:"",summary:"",overview:"",challenge:"",approach:"",checks:"",takeaway:"",glance:[],facts:[],deliverables:[],hero:"",images:[],cover:"",approved:false,visibility:"draft",scopeVerified:false,deliverablesVerified:false};
  setDraft({...draft,projects:[...draft.projects,p]});setSelected(code);navigate("projects");
 }
 async function save(publish:boolean){if(!draft||!state)return;setBusy(true);setError("");setMessage("");setConfirm(false);
  try{const r=await fetch("/api/admin/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({document:draft,revision:state.revision,publish})});const d=await r.json() as CMSState & {error:string;enquiries:Enquiry[]};if(!r.ok)throw new Error(d.error);setState(d);setDraft(d.draft);setMessage(publish?"Published. The website now uses these approved changes.":"Draft saved. The public website has not changed.")}
  catch(e){setError(e instanceof Error?e.message:"Changes could not be saved.")}finally{setBusy(false)}
 }
 async function signOut(){if(dirty&&!window.confirm("Discard unsaved changes and sign out?"))return;try{const response=await fetch("/api/admin/session",{method:"DELETE"});if(!response.ok)throw new Error("Sign-out failed. Please try again.");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Sign-out failed.")}}
 const project=draft?.projects.find(p=>p.code===selected);
 const ready=draft?.projects.filter(p=>p.visibility==="published"&&p.approved)||[];
 const imageCount=draft?.projects.reduce((n,p)=>n+p.images.length,0)||0;
 const filtered=draft?.projects.filter(p=>(filter==="all"||p.visibility===filter)&&(p.title+" "+p.code+" "+p.category).toLowerCase().includes(query.toLowerCase()))||[];
 return <main className="cp cp-shell">
  <aside className={"cp-sidebar "+(nav?"is-open":"")}><a className="cp-brand" href="/admin"><img src="/jn-logo-mark.png" width={66} height={48} alt="Julkar Naeem"/><span>JULKAR NAEEM<small>CONTROL PANEL</small></span></a><p className="cp-nav-label">WEBSITE MANAGEMENT</p><nav aria-label="Control panel">{sections.map(({id,label,icon:Icon})=><button key={id} aria-current={section===id?"page":undefined} onClick={()=>navigate(id)}><Icon size={19}/>{label}{id==="projects"&&<span className="cp-count">{draft?.projects.length??"—"}</span>}</button>)}</nav><div className="cp-sidebar-bottom"><p><ShieldCheck size={17}/> Owner workspace</p><a href="https://julkarnaeem.com/" target="_blank" rel="noopener noreferrer">julkarnaeem.com <ArrowUpRight size={15}/></a><button onClick={signOut}><LogOut size={17}/> Sign out</button></div></aside>
  <div className="cp-main"><header className="cp-topbar"><div><button className="cp-menu" aria-label="Toggle navigation" aria-expanded={nav} onClick={()=>setNav(!nav)}><Menu/></button><span className="cp-breadcrumb">Workspace <ChevronRight size={14}/> <strong>{sections.find(s=>s.id===section)?.label}</strong></span></div><a className="cp-outline" href="https://julkarnaeem.com/" target="_blank" rel="noopener noreferrer">View website <ArrowUpRight size={16}/></a></header>
  <div className="cp-workspace">{local&&<p className="cp-local">Local preview · changes are saved on this computer. Production publishing needs the website database.</p>}
  <div className="cp-page-heading"><div><p className="cp-eyebrow">JULKARNAEEM.COM</p><h1>{section==="overview"?"Website overview":sections.find(s=>s.id===section)?.label}</h1><p>{section==="overview"?"Keep your work current. Publish only what is ready to be seen.":section==="projects"?"Manage accurate case studies and authorised 3D model views.":"One website. One content source."}</p></div><div className="cp-heading-actions"><button className="cp-outline" onClick={()=>save(false)} disabled={!draft||busy||!dirty}><Save size={16}/>{busy?"Saving…":"Save draft"}</button><button className="cp-button" onClick={()=>setConfirm(true)} disabled={!draft||busy||!unpublished}><Globe size={16}/>Publish changes</button></div></div>
  <div aria-live="polite">{message&&<p className="cp-success"><Check size={17}/>{message}</p>}</div>{error&&<p className="cp-error" role="alert">{error}</p>}
  {!draft?<div className="cp-panel">{error?"Content could not be loaded. Your website content remains unchanged.":"Loading your website content…"}</div>:<>
  {section==="overview"&&<><div className="cp-stats">{[{n:draft.projects.length,label:"Portfolio projects",icon:FolderOpen},{n:ready.length,label:"Approved to publish",icon:ShieldCheck},{n:imageCount,label:"3D model views",icon:Images},{n:draft.settings.services.length,label:"Core services",icon:BriefcaseBusiness}].map(({n,label,icon:Icon})=><article key={label}><Icon size={20}/><strong>{String(n).padStart(2,"0")}</strong><span>{label}</span></article>)}</div>
   <div className="cp-overview-grid"><section className="cp-panel"><div className="cp-panel-heading"><div><p className="cp-eyebrow">SELECTED WORK</p><h2>Your portfolio</h2></div><button className="cp-text-button" onClick={()=>navigate("projects")}>Manage projects <ArrowUpRight size={16}/></button></div><div className="cp-project-overview">{draft.projects.map(p=><button key={p.code} onClick={()=>{setSelected(p.code);navigate("projects")}}>{approvedMediaUrl(p.cover)&&<img src={cloud(p.cover,480)} alt={p.title+" model"} width={104} height={80}/>}<span><strong>{p.title||"Untitled project"}</strong><small>JN-PRJ-{p.code} · {p.category||"Set category"}</small></span><span className={"cp-status "+p.visibility}>{p.visibility}</span><ChevronRight size={16}/></button>)}</div></section>
   <div><section className="cp-panel cp-publish-card"><ShieldCheck size={30}/><p className="cp-eyebrow">PUBLICATION CONTROL</p><h2>Accuracy before publication.</h2><p>Save edits as a draft. Review the scope, facts and images before publishing them to the website.</p><dl><div><dt>Last published</dt><dd>{date(state?.publishedAt??null)}</dd></div><div><dt>Draft status</dt><dd>{dirty?"Unsaved changes":unpublished?"Saved · awaiting publication":"Up to date"}</dd></div></dl><button className="cp-outline" onClick={()=>navigate("settings")}>Publishing settings <ChevronRight size={16}/></button></section><section className="cp-panel cp-brand-note"><p className="cp-eyebrow">FABRICATION-DRIVEN</p><p>A model that looks correct is not enough. The steel must also be practical to fabricate and erect.</p><small>Keep this principle at the centre of every project story.</small></section></div></div></>}
  {section==="projects"&&<><div className="cp-toolbar"><label className="cp-search"><Search size={18}/><input aria-label="Search portfolio projects" placeholder="Search project title, code or category" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter project visibility" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All projects</option><option value="published">Published</option><option value="draft">Drafts</option><option value="archived">Archived</option></select><button className="cp-button" onClick={addProject}><Plus size={18}/>Add project</button></div><div className="cp-project-layout"><div className="cp-project-list">{filtered.map(p=><button key={p.code} className={selected===p.code?"selected":""} onClick={()=>setSelected(p.code)}>{approvedMediaUrl(p.cover)&&<img src={cloud(p.cover,480)} alt="" width={90} height={76}/>}<span><small>JN-PRJ-{p.code}</small><strong>{p.title||"Untitled project"}</strong><span className={"cp-status "+p.visibility}>{p.visibility}</span></span></button>)}{!filtered.length&&<p className="cp-empty">No projects match this search.</p>}</div>{project&&<section className="cp-panel cp-editor" key={project.code}><div className="cp-panel-heading"><div><p className="cp-eyebrow">JN-PRJ-{project.code}</p><h2>{project.title||"New project"}</h2></div>{state?.published.projects.some(p=>p.code===project.code&&p.visibility!=="draft")&&<a className="cp-text-button" href={"https://julkarnaeem.com/portfolio/"+project.slug} target="_blank" rel="noopener noreferrer">Live case study <ArrowUpRight size={15}/></a>}</div>
   <div className="cp-form-grid"><Field label="Project title" value={project.title} onChange={v=>editProject({title:v})}/><Field label="Project URL slug" value={project.slug} readOnly={state?.published.projects.some(p=>p.code===project.code&&p.visibility!=="draft")} onChange={v=>editProject({slug:v})} hint="Existing URLs stay permanent."/><Field label="Project type" value={project.type} onChange={v=>editProject({type:v})}/><Field label="Structure category" value={project.category} onChange={v=>editProject({category:v})}/></div>
   <Field label="Project summary" value={project.summary} multiline onChange={v=>editProject({summary:v})}/>
   <details className="cp-details" open><summary>Case-study narrative</summary>{([["overview","Project overview"],["challenge","Challenge / constraint"],["approach","Detailing approach"],["checks","Fabrication & constructability checks"],["takeaway","Practical takeaway"]] as const).map(([key,label])=><Field key={key} label={label} value={project[key]} multiline onChange={v=>editProject({[key]:v})}/>)}</details>
   <details className="cp-details"><summary>Verified facts & deliverables</summary><p className="cp-help">Only include information supported by project records. Leave unknown fields out.</p><LineField key={"Project at a glance"+state?.revision} label="Project at a glance" hint="One fact per line: Label | Verified value" value={project.glance.map(p=>p.join(" | ")).join("\n")} onChange={v=>{const pairs=v.split("\n").filter(Boolean).map(line=>{const i=line.indexOf("|");return i<0?[line,""]:[line.slice(0,i),line.slice(i+1)]}) as [string,string][];editProject({glance:pairs,facts:pairs})}}/><LineField key={"Produced deliverables"+state?.revision} label="Produced deliverables" hint="One deliverable per line. Leave empty when not publicly confirmed." value={project.deliverables.join("\n")} onChange={v=>editProject({deliverables:v.split("\n").filter(Boolean)})}/><label className="cp-check"><input type="checkbox" checked={project.scopeVerified} onChange={e=>editProject({scopeVerified:e.target.checked})}/>The stated scope is supported by project records.</label><label className="cp-check"><input type="checkbox" checked={project.deliverablesVerified} onChange={e=>editProject({deliverablesVerified:e.target.checked})}/>The listed deliverables were actually produced and may be shared.</label></details>
   <details className="cp-details" open><summary>Cloudinary model gallery</summary><LineField key={"Approved 3D image URLs"+state?.revision} label="Approved 3D image URLs" hint="One delivery URL per line. Restricted drawing types are blocked." value={project.images.map(m=>m.url).join("\n")} onChange={v=>{const images=v.split("\n").filter(Boolean).map(url=>({url:url.trim(),name:url.trim().split("/").pop()||"3D model"}));editProject({images,...(!images.some(m=>m.url===project.cover)?{cover:images[0]?.url||""}:{})})}}/><div className="cp-gallery">{project.images.filter(m=>approvedMediaUrl(m.url)).map(m=><label key={m.url}><img src={cloud(m.url,480)} alt={project.title+" approved model view"} width={160} height={120}/><span><input type="radio" name="cover" checked={project.cover===m.url} onChange={()=>editProject({cover:m.url})}/>Use as cover</span></label>)}</div></details>
   <div className="cp-publication"><h3>Portfolio visibility</h3><label className="cp-check"><input type="checkbox" checked={project.approved} onChange={e=>editProject({approved:e.target.checked,...(!e.target.checked?{visibility:"draft" as const}:{})})}/>I have permission to publish this content and every selected image.</label><label className="cp-field"><span>Publication status</span><select value={project.visibility} onChange={e=>editProject({visibility:e.target.value as CMSProject["visibility"]})}><option value="draft">Draft — keep private</option><option value="published">Published — show on the website</option><option value="archived">Archived — remove from public portfolio</option></select></label><p className="cp-help">Save draft first, then publish changes to update the website. Client identities and restricted technical drawings stay private.</p></div>
  </section>}</div></>}
  {section==="website"&&<div className="cp-content-columns"><section className="cp-panel"><h2>Homepage & introduction</h2><Field label="Hero headline" value={draft.settings.heroLead} onChange={v=>setting("heroLead",v)}/><Field label="Hero gold emphasis" value={draft.settings.heroAccent} onChange={v=>setting("heroAccent",v)}/><Field label="Hero supporting text" multiline value={draft.settings.heroIntro} onChange={v=>setting("heroIntro",v)}/><Field label="Professional introduction" multiline value={draft.settings.aboutIntro} onChange={v=>setting("aboutIntro",v)}/><Field label="Final enquiry headline" value={draft.settings.ctaTitle} onChange={v=>setting("ctaTitle",v)}/></section><section className="cp-panel"><h2>Contact & professional profiles</h2><LineField key={"Professional emails"+state?.revision} label="Professional emails" value={draft.settings.professionalEmails.join("\n")} onChange={v=>setting("professionalEmails",v.split("\n").filter(Boolean))}/><Field label="WhatsApp number" value={draft.settings.whatsappNumber} onChange={v=>setting("whatsappNumber",v)}/>{(["linkedInUrl","upworkUrl","instagramUrl"] as const).map(k=><Field key={k} label={{linkedInUrl:"LinkedIn",upworkUrl:"Upwork",instagramUrl:"Instagram"}[k]} value={draft.settings[k]} onChange={v=>setting(k,v)}/>)}<p className="cp-help">Empty contact methods are hidden on the website. Only use verified professional details.</p></section><section className="cp-panel cp-wide"><h2>Page titles & search descriptions</h2><p className="cp-help">Canonical URLs and routes remain fixed. Project metadata follows each project’s title and summary.</p>{Object.entries(draft.settings.pageInfo).map(([key,value])=><details className="cp-details" key={key}><summary>/{key}</summary><Field label="Page title" value={value.title} onChange={v=>setting("pageInfo",{...draft.settings.pageInfo,[key]:{...value,title:v}})}/><Field label="Search description" multiline value={value.description} onChange={v=>setting("pageInfo",{...draft.settings.pageInfo,[key]:{...value,description:v}})}/></details>)}</section></div>}
  {section==="services"&&<div className="cp-services">{draft.settings.services.map((s,i)=><section className="cp-panel" key={s.id}><img src={"/services/"+s.image+".webp"} width={320} height={180} alt={s.title+" illustration"}/><p className="cp-eyebrow">SERVICE {String(i+1).padStart(2,"0")}</p><Field label="Service name" value={s.title} onChange={v=>setting("services",draft.settings.services.map((item,n)=>n===i?{...item,title:v}:item))}/><Field label="Service description" multiline value={s.text} onChange={v=>setting("services",draft.settings.services.map((item,n)=>n===i?{...item,text:v}:item))}/><a className="cp-subtle-link" href={"https://julkarnaeem.com/services#"+s.id} target="_blank" rel="noopener noreferrer">View service <ArrowUpRight size={14}/></a></section>)}</div>}
  {section==="enquiries"&&<section className="cp-panel"><div className="cp-panel-heading"><div><h2>Project enquiries</h2><p className="cp-help">Latest 100 messages from the existing website form. Reading messages does not send a reply.</p></div><Inbox size={26}/></div>{inboxLoading?<p>Loading enquiries…</p>:inboxError?<p className="cp-notice" role="status">{inboxError}</p>:!enquiries.length?<div className="cp-empty"><Inbox size={34}/><h3>No enquiries yet</h3><p>Genuine website submissions will appear here.</p></div>:enquiries.map(e=><details className="cp-details" key={e.id}><summary>{e.name} · {e.company}<small>{new Date(e.created_at).toLocaleDateString()}</small></summary><p>{e.country} · {e.project_type}</p><a href={"mailto:"+e.email}>{e.email}</a><pre className="cp-message">{(()=>{try{const d=JSON.parse(e.details);return Object.entries(d).filter(([,v])=>String(v)).map(([k,v])=>k+": "+(Array.isArray(v)?v.join(", "):String(v))).join("\n\n")}catch{return e.details}})()}</pre></details>)}</section>}
  {section==="settings"&&<div className="cp-content-columns"><section className="cp-panel"><ShieldCheck size={28}/><h2>Publishing & access</h2><dl className="cp-settings-list"><div><dt>Administration address</dt><dd>admin.julkarnaeem.com</dd></div><div><dt>Website</dt><dd>julkarnaeem.com</dd></div><div><dt>Content source</dt><dd>{local?"Local development store":"Website PostgreSQL database"}</dd></div><div><dt>Last saved</dt><dd>{date(state?.updatedAt||null)}</dd></div><div><dt>Last published</dt><dd>{date(state?.publishedAt||null)}</dd></div></dl><p className="cp-help">The subdomain must be connected to the same hosting project as the website. The /admin route works in either location.</p></section><section className="cp-panel"><FileText size={28}/><h2>Your publication checks</h2><ul className="cp-checklist"><li>Confirm project facts before marking the scope verified.</li><li>Use approved Cloudinary 3D model images only.</li><li>Keep client names and restricted drawings private.</li><li>Save a draft before publishing.</li><li>Archive a project to hide it without losing its record.</li></ul><p className="cp-help">Each save checks for concurrent changes and preserves a previous content revision. An expired session requires signing in again.</p></section></div>}
  </>}</div><footer className="cp-bottom"><span>JULKAR NAEEM · WEBSITE CONTROL PANEL</span><span>{dirty?"Unsaved changes":unpublished?"Draft changes awaiting publication":"Content up to date"}</span></footer></div>
  <Dialog open={confirm} onOpenChange={setConfirm}><DialogContent className="cp cp-dialog"><DialogTitle>Publish website changes?</DialogTitle><DialogDescription>This updates the live website using the current content and the {ready.length} approved projects marked Published. Draft and archived projects stay outside the public portfolio.</DialogDescription><p>Check all project claims, image permissions and contact details before publishing.</p><div className="cp-heading-actions"><button className="cp-outline" onClick={()=>setConfirm(false)}>Keep editing</button><button className="cp-button" onClick={()=>save(true)} disabled={busy}>Publish approved changes</button></div></DialogContent></Dialog>
 </main>
}
