import media from './media.json';
export const config={name:'Julkar Naeem',title:'Senior Structural Steel Detailer / Detailing Engineer',origin:'https://julkarnaeem.com',email:'',phone:'',whatsapp:'',socials:[] as {name:string,url:string}[]};
export const services=[
{id:'tekla-modelling',title:'Tekla 3D modelling',text:'Coordinated structural-steel models with clear member orientation, levels and interfaces before drawing production.',image:'tekla'},
{id:'fabrication-drawings',title:'Shop & fabrication drawings',text:'Assembly and single-part drawings that communicate how each piece is cut, welded, bolted and assembled.',image:'shop'},
{id:'erection-drawings',title:'GA & erection drawings',text:'Clear member identification, dimensions and levels to support site coordination and the erection sequence.',image:'ga'},
{id:'connection-detailing',title:'Connection detailing',text:'Translate approved connection requirements into legible model and drawing details, with access and tool clearance in mind.',image:'connection'},
{id:'miscellaneous-steel',title:'Stairs, handrails & miscellaneous steel',text:'Practical stair detailing, platform and walkway detailing, handrails and grating coordinated with surrounding steel.',image:'stairs'},
{id:'material-reports',title:'MTO & BOM reporting',text:'Organised material quantities, bolt lists and agreed production files drawn from the coordinated model.',image:'mto'}];
export const deliverables=['3D Tekla models','GA drawings','Assembly drawings','Single-part drawings','Shop and fabrication drawings','Erection drawings','Anchor-bolt plans','Connection details','Bolt lists','MTO and BOM reports'];
export const formats=['NC','CNC','DXF','DWG','IFC'];
export const checks=['Fabrication access','Welding access','Bolt installation and tightening access','Tool clearance','Member orientation','Clashes','Erection feasibility','Dimensions and levels','Drawing clarity','Missing or conflicting information'];
export const steps=[['Review project information','Read the supplied engineering drawings, specifications and revision history.'],['Confirm scope and deliverables','Agree the steelwork included, drawing requirements, file formats and programme.'],['Identify missing or conflicting information','Check dimensions, levels, member references and interfaces before assumptions become modelled details.'],['Raise RFIs','Record focused questions and track responses from the responsible project team.'],['Build and coordinate the Tekla model','Develop the model against the agreed information and coordinate member geometry and interfaces.'],['Review fabrication and erection practicality','Examine access, orientation, clashes and the practical sequence of assembly.'],['Produce drawings and reports','Prepare agreed fabrication documentation, erection information and material reports.'],['Complete internal checks','Review the model, drawing clarity, dimensions, marks and issue consistency.'],['Issue deliverables and manage revisions','Issue the agreed package and maintain clear revision records as project information changes.']];
const seeds=[
{code:'001',slug:'poolside-restaurant-shed',title:'Poolside Restaurant Shed',type:'Commercial',category:'PEB & portal frames',summary:'A single-storey PEB restaurant shed beside a resort swimming pool in Bangladesh. Main structural steelwork was modelled in Tekla Structures 2025, with fabrication and erection documentation.',focus:'Fabrication access, bolt-tightening access and member orientation were the key portfolio themes. Erection-drawing clarity connects the model to site use.',approach:'A practical review follows the main frame from member orientation to connection access, then checks how clearly the erection information communicates the steelwork.',facts:[['Building type','PEB commercial building'],['Location','Bangladesh'],['Area','Approximately 385 m²'],['Steel quantity','Approximately 17 tonnes'],['Software','Tekla Structures 2025']],hero:'3D-SCREENSHOT-02'},
{code:'002',slug:'multi-storey-steel-frame',title:'Multi-storey Steel Frame',type:'Multi-storey',category:'Beam & column frames',summary:'A multi-level beam-and-column model with repeated floor framing and a pitched roof. The open model views make the relationship between primary members and secondary framing easy to examine.',focus:'Floor-to-floor member alignment, repeated beam interfaces and the transition to sloping roof framing are the visible coordination considerations.',approach:'Review one framing bay in detail, then check repeated conditions across the model. Compare beam orientation and level changes before preparing consistent member references.',facts:[['Visible structure','Multi-level beam-and-column frame'],['Roof form','Pitched steel roof framing']],hero:'3D-SCREENSHOT-01'},
{code:'003',slug:'braced-multi-storey-building',title:'Braced Multi-storey Steel Building',type:'Multi-storey',category:'Braced frames',summary:'A multi-storey steel model with repeated floor framing, diagonal bracing and internal stairs. The overall view brings the vertical circulation and bracing interfaces into the same coordination picture.',focus:'The interaction of bracing, floor beams and stairs calls for close attention to member orientation, local access and clear level references.',approach:'Use overall views to understand the framing arrangement and focused views to review congested interfaces. Keep questions about conflicting information traceable through the RFI process.',facts:[['Visible structure','Braced multi-storey frame'],['Visible elements','Floor beams, diagonal bracing and stairs']],hero:'3D-SCREENSHOT-01'},
{code:'004',slug:'industrial-portal-frame-building',title:'Industrial Portal-frame Building',type:'Industrial',category:'PEB & portal frames',summary:'A rectangular industrial building model with a pitched roof and smaller entrance canopies. Model views allow the primary steel arrangement and secondary roof and wall members to be explored together.',focus:'The main framing, secondary members and canopy interfaces need a consistent approach to orientation and clear identification of local changes.',approach:'Review the primary frame first, then the secondary members and perimeter interfaces. Compare model views so repetitive conditions and local exceptions remain clear.',facts:[['Visible structure','Pitched-roof industrial building'],['Visible interfaces','Main building and entrance canopies']],hero:'3D-SCREENSHOT-02'},
{code:'005',slug:'maintenance-walkway-caged-ladders',title:'Maintenance Walkway & Caged Ladders',type:'Access steel',category:'Platforms & walkways',summary:'An elevated access walkway model with a change in direction, handrails, support steel and caged ladders. The views highlight the relationship between the access route and its supporting frame.',focus:'Walkway corners, ladder interfaces, handrail continuity and the transition at the end of the access route are the visible detailing considerations.',approach:'Follow the access route through the model. Review clearances, support orientation, grating boundaries and how separate assemblies meet at changes in direction.',facts:[['Visible structure','Elevated maintenance walkway'],['Visible elements','Handrails, support steel and caged ladders']],hero:'3D-SCREENSHOT-01'}];
export const projects=seeds.map(p=>({...p,images:media.filter(m=>m.name.startsWith('JN-PRJ-'+p.code)).sort((a,b)=>a.name.localeCompare(b.name)),cover:media.find(m=>m.name==='JN-PRJ-'+p.code+'-'+p.hero)!.url}));
export const cloud=(url:string,width=1200)=>url.replace('f_auto,q_auto',`f_auto,q_auto,c_limit,w_${width}`);
export const pageInfo:Record<string,{title:string,description:string}>={services:{title:'Structural Steel Detailing Services',description:'Tekla steel detailing, steel shop drawings, erection drawings, connection detailing and material reporting for fabrication teams.'},portfolio:{title:'Steel Detailing Project Experience',description:'Explore five structural-steel modelling case studies: PEB framing, multi-storey structures, industrial steel and maintenance walkways.'},process:{title:'The Steel Detailing Process',description:'From project review and RFIs to Tekla model coordination, fabrication checks, drawing issue and revision management.'},about:{title:'About Julkar Naeem',description:'Senior Structural Steel Detailer based in Dhaka, with experience across steel, construction, production, QA and operations.'},credentials:{title:'Training & Credentials',description:'AISC Detailer Training Series and Tekla Structures Steel Fundamentals, supporting practical structural-steel detailing.'},contact:{title:'Request a Project Review',description:'Discuss Tekla modelling, fabrication drawings and structural-steel detailing support. Send your scope, deliverables and schedule.'},privacy:{title:'Privacy',description:'How project enquiries and contact information are handled on the Julkar Naeem structural-steel detailing website.'}};
